package exception;

public class WrongObjectStateException extends Exception {

	/**
	 * default generated by IDE
	 */
	private static final long serialVersionUID = 1L;
	private String message;
	
	public WrongObjectStateException(String message) {
		this.message = message;
	}
	
	@Override
	public String getMessage() {
		return message;
	}
	
}
